created placeholders for profile page
brett-buskirk/rc-journey pull request #19
Opened 2021-11-21 01:52 UTC by KaOus22

Created a rough draft of the profile page. This will be dynamic so once we have the db completely scaffolded there will not be images hardcoded in the html like this.

2021-11-21 05:04 UTC, brett-buskirk commented
This looks good to me, @KaOus22! I'll push it through.

2021-11-21 05:09 UTC, brett-buskirk requested changes
Looks good other than where you changed the link in the dashboard. The link was supposed to be `editprofile` and not `profile`. The intention is that a user can edit their own profile from the dashboard. The `profile` link is for when they click on the post of another user and it takes them to that user's profile page.

2021-11-21 05:09 UTC, brett-buskirk commented on rcjourney/rcapp/templates/dashboard.html
> -        <a class="nav-link" href="{% url 'editprofile' %}">Profile</a>
This was intentional. The dashboard is the only place a user can go and edit their profile from. This should be changed back to `editprofile`.

2021-11-22 02:58 UTC, KaOus22 commented on rcjourney/rcapp/templates/dashboard.html
> -        <a class="nav-link" href="{% url 'editprofile' %}">Profile</a>
Upon pushing the changes up I got a message that says the repo was changed..

2021-11-22 05:33 UTC, brett-buskirk approved these changes

2021-11-22 05:34 UTC, merged